/**********************************************************************************
 * gd.cpp
 *
 * Example driver for convergent extension generated by *global gradient descent*
 * on the edge tensions of a vertex-model tissue.
 *
 * The task is encoded in the cost function
 *
 *      C = ( eps_target - eps )^2,
 *
 * where eps is the pure-shear strain of the tissue -- the box degree of freedom
 * that is relaxed together with the vertex positions -- and eps_target is the
 * prescribed deformation. The tunable degrees of freedom, the active edge
 * tensions, follow
 *
 *      d Lambda_ij / dt = - gamma_GD  dC / d Lambda_ij .
 *
 * Unlike the local rules, computing dC/dLambda_ij requires knowing how the whole
 * tissue responds to a change of a single junction, which is exactly the
 * "external processor" the paper contrasts with decentralized feedback. Here the
 * derivative is obtained numerically, by central finite differences: each
 * junction in turn is perturbed by +/- h, the tissue is re-relaxed, and the
 * resulting strain is recorded. That makes one tuning step cost O(N_junctions)
 * full minimizations, so this driver is far more expensive than local_rule.cpp
 * and is practical only for the small systems used here.
 *
 * Protocol:
 *   1) Build a force-balanced tissue with uniform preferences.
 *   2) Search over (p0 distribution, active-tension distribution) for an initial
 *      state matching experiment at the onset of convergent extension.
 *   3) Alternate: one gradient-descent update of all tensions, then a full FIRE
 *      relaxation of the vertex positions and the box pure-shear strain.
 *
 * Dependencies:
 *   cellGPU (Daniel Sussman group) plus project-specific extensions to the
 *   vertex-model classes.  https://github.com/sussmanLab/cellGPU
 *
 * Last updated: August 7, 2026
 **********************************************************************************/

#include "std_include.h"
#include "cuda_runtime.h"
#include "cuda_profiler_api.h"

#define ENABLE_CUDA

#include "Simulation.h"
#include "voronoiQuadraticEnergy.h"
#include "selfPropelledParticleDynamics.h"
#include "selfPropelledCellVertexDynamics.h"
#include "vertexQuadraticEnergy.h"
#include "DatabaseNetCDFSPV.h"
#include "DatabaseNetCDFAVM.h"
#include "EnergyMinimizerFIRE2D.h"

using std::cout;
using std::endl;
using std::ofstream;
using std::string;

// ---------------------------------------------------------------------------
// Driver-local helpers.
//
// These are repeated verbatim in each of the three example drivers so that
// every file can be read on its own; they are not part of the vertex-model
// library.
// ---------------------------------------------------------------------------

static std::string intToString(int value)
{
    std::ostringstream ss;
    ss << value;
    return ss.str();
}

//! Convenience wrapper for the FIRE minimizer settings.
static void setFIREParameters(shared_ptr<EnergyMinimizerFIRE> fire,
                              Dscalar deltaT,
                              Dscalar alphaStart,
                              Dscalar deltaTMax,
                              Dscalar deltaTInc,
                              Dscalar deltaTDec,
                              Dscalar alphaDec,
                              int nMin,
                              Dscalar forceCutoff)
{
    fire->setDeltaT(deltaT);
    fire->setAlphaStart(alphaStart);
    fire->setDeltaTMax(deltaTMax);
    fire->setDeltaTInc(deltaTInc);
    fire->setDeltaTDec(deltaTDec);
    fire->setAlphaDec(alphaDec);
    fire->setNMin(nMin);
    fire->setForceCutoff(forceCutoff);
}

/*!
 * Build a sweep of n values on the half-open grid
 *      low, low + d, ..., high - d      with d = (high - low)/n,
 * i.e. the upper bound is approached but not reached. This is the grid used for
 * the parameter scans in the paper; if you want the endpoint included, use
 * (high - low)/(n - 1) instead.
 */
static std::vector<double> buildLinearGrid(int n, Dscalar low, Dscalar high)
{
    std::vector<double> values;
    if (n <= 0)
        return values;

    values.resize(n);
    for (int i = 0; i < n; ++i)
        values[i] = low + ((high - low) / n) * i;
    return values;
}

/*!
 * Run FIRE on an already-configured minimizer/simulation pair until the tissue
 * is force balanced. The minimizer is restarted
 * `outerRounds` times with an increasing iteration budget, which is how the
 * project code gets past configurations FIRE initially struggles with; the loop
 * exits as soon as max_m |f_m| drops below forceTol.
 *
 * earlyAbortForce > 0 enables an additional escape hatch used during the
 * initial-condition search: a sample still far from force balance after a third
 * of the rounds is abandoned rather than pursued, since drawing another random
 * initial state is cheaper than forcing this one to converge.
 *
 * Returns the final max residual force.
 */
static Dscalar runFireLoop(shared_ptr<EnergyMinimizerFIRE> fire,
                           SimulationPtr sim,
                           Dscalar fireDt,
                           Dscalar forceTol,
                           int outerRounds,
                           int innerIterations,
                           Dscalar earlyAbortForce = -1.0)
{
    Dscalar maxForce = 0.0;
    for (int round = 0; round < outerRounds; ++round)
    {
        setFIREParameters(fire, fireDt, 0.15, 10 * fireDt, 1.1, 0.5, .99, 5, forceTol);
        fire->setMaximumIterations(innerIterations * (round + 1));
        sim->performTimestep();

        maxForce = fire->getMaxForce();
        if (maxForce < forceTol)
            break;

        if ((earlyAbortForce > 0.0) && (round > outerRounds / 3) && (maxForce > earlyAbortForce))
            break;
    }
    return maxForce;
}

/*!
 * Build a fresh FIRE minimizer for the tissue and relax it to force balance.
 */
static Dscalar runFireMinimization(shared_ptr<VertexQuadraticEnergy> avm,
                                   bool useGPU,
                                   Dscalar fireDt,
                                   Dscalar forceTol,
                                   int outerRounds,
                                   int innerIterations,
                                   Dscalar earlyAbortForce = -1.0)
{
    shared_ptr<EnergyMinimizerFIRE> fire = make_shared<EnergyMinimizerFIRE>(avm);
    SimulationPtr sim = make_shared<Simulation>();
    sim->setConfiguration(avm);
    sim->addUpdater(fire, avm);
    sim->setIntegrationTimestep(fireDt);
    sim->setCPUOperation(!useGPU);

    return runFireLoop(fire, sim, fireDt, forceTol, outerRounds, innerIterations, earlyAbortForce);
}

/*!
 * Append one record of tissue observables to the summary file. The column
 * layout is identical in all three example drivers:
 *
 *    1  step index (tension-update iteration or strain step; -1 = reference state)
 *    2  mean target perimeter p0 of the cell population
 *    3  total energy E
 *    4  area contribution to E
 *    5  perimeter contribution to E
 *    6  active tension contribution to E,  sum_ij Lambda_ij l_ij
 *    7  mean target shape index p0
 *    8  variance of the target shape index
 *    9  mean cell shape index  p = P / sqrt(A)     
 *   10  variance of the cell shape index
 *   11  tissue pure-shear strain eps
 *   12  max residual force at the end of the relaxation
 */
static void writeSummaryLine(ofstream &outFile,
                             int step,
                             Dscalar p0Mean,
                             Dscalar strain,
                             shared_ptr<VertexQuadraticEnergy> avm,
                             Dscalar maxForce)
{
    Dscalar3 virialStress = avm->computeStressComponents();
    Dscalar2 energyTerms = avm->computeEnergyTerms();
    Dscalar tensionEnergy = avm->computeEdgeTensionEnergyTerm();

    outFile << step << " " << p0Mean << " " << avm->computeEnergy() << " "
            << energyTerms.x << " " << energyTerms.y << " " << tensionEnergy << " "
             << " " << avm->reportq0() << " " << avm->reportVarq0() << " "
            << avm->reportq() << " " << avm->reportVarq() << " "
            << strain << " " << maxForce << endl;
}

// ---------------------------------------------------------------------------
// Numerical gradient of the cost function with respect to the edge tensions
// ---------------------------------------------------------------------------

/*!
 * Directed-edge index of the junction v1 -> v2, i.e. the k with
 * vertexNeighbors[3*v1 + k] == v2. Returns -1 if v2 is not a neighbour of v1.
 */
static int directedEdgeIndex(const ArrayHandle<int> &h_vn, int v1, int v2)
{
    for (int k = 0; k < 3; ++k)
    {
        if (h_vn.data[3 * v1 + k] == v2)
            return 3 * v1 + k;
    }
    return -1;
}

/*!
 * Fill avm->EdgeTensionGrad with the central finite-difference estimate of
 *
 *      dC / d Lambda_ij ,      C = (eps_target - eps)^2 .
 *
 * For each junction:
 *   - both directed copies of its tension are shifted by -h, the tissue is
 *     re-relaxed (vertex positions *and* box strain), and eps is recorded;
 *   - the same is done for +h;
 *   - the gradient (C(+h) - C(-h)) / 2h is stored on both copies;
 *   - the tension is restored and the tissue re-relaxed once more, so that the
 *     next junction is perturbed around the same reference configuration.
 *
 * Cost: three full minimizations per junction, i.e. O(N) minimizations per
 * tuning step.
 *
 * Two implementation notes:
 *   - Relaxations inside this routine use their own, tighter tolerance: the
 *     finite-difference signal is the small strain change induced by h, so any
 *     residual force noise must be well below it.
 *   - The perturbation h must be small enough that no T1 transition is triggered
 *     during these relaxations. A T1 would rewire the network and invalidate
 *     both the neighbour table cached here and the edge-to-index mapping of the
 *     reference tensions. In practice this is not a problem because the tissue
 *     starts each perturbation from a relaxed configuration and h is small, but
 *     it is worth keeping in mind when changing FiniteDiffStep.
 */
static void computeEdgeTensionGradientsFiniteDifference(shared_ptr<VertexQuadraticEnergy> avm,
                                                        Dscalar epsilonTarget,
                                                        Dscalar h,
                                                        Dscalar fdFireDt,
                                                        Dscalar fdForceTol,
                                                        int fdOuterRounds,
                                                        int fdInnerIterations)
{
    const int numVertices = avm->Nvertices;
    const int numEdges = 3 * numVertices;

    ArrayHandle<Dscalar> h_etGrad(avm->EdgeTensionGrad, access_location::host, access_mode::overwrite);
    ArrayHandle<Dscalar> h_et(avm->EdgeTension, access_location::host, access_mode::readwrite);
    ArrayHandle<int> h_vn(avm->vertexNeighbors, access_location::host, access_mode::read);

    // Reference tensions to perturb around, and a zeroed gradient array.
    std::vector<Dscalar> referenceTensions(numEdges);
    for (int i = 0; i < numEdges; ++i)
    {
        referenceTensions[i] = h_et.data[i];
        h_etGrad.data[i] = 0.0;
    }

    // The strain response is what we differentiate, so the box pure-shear
    // degree of freedom must be free during these relaxations.
    avm->setBoxStrainXStrainY_DOF(true);

    shared_ptr<EnergyMinimizerFIRE> fire = make_shared<EnergyMinimizerFIRE>(avm);
    SimulationPtr sim = make_shared<Simulation>();
    sim->setConfiguration(avm);
    sim->addUpdater(fire, avm);
    sim->setIntegrationTimestep(fdFireDt);
    sim->setCPUOperation(true);

    for (int v1 = 0; v1 < numVertices; ++v1)
    {
        for (int dir = 0; dir < 3; ++dir)
        {
            int v2 = h_vn.data[3 * v1 + dir];

            // Visit each undirected junction once, at its lower-index endpoint.
            if ((v2 <= v1) || (v2 >= numVertices))
                continue;

            int forwardIndex = 3 * v1 + dir;
            int reverseIndex = directedEdgeIndex(h_vn, v2, v1);
            if (reverseIndex < 0)
                continue;

            // --- perturb by -h ---
            h_et.data[forwardIndex] = referenceTensions[forwardIndex] - h;
            h_et.data[reverseIndex] = referenceTensions[reverseIndex] - h;
            runFireLoop(fire, sim, fdFireDt, fdForceTol, fdOuterRounds, fdInnerIterations);
            Dscalar epsMinus = avm->ReturnStrainXStrainY().x;

            // --- perturb by +h ---
            h_et.data[forwardIndex] = referenceTensions[forwardIndex] + h;
            h_et.data[reverseIndex] = referenceTensions[reverseIndex] + h;
            runFireLoop(fire, sim, fdFireDt, fdForceTol, fdOuterRounds, fdInnerIterations);
            Dscalar epsPlus = avm->ReturnStrainXStrainY().x;

            Dscalar costMinus = (epsilonTarget - epsMinus) * (epsilonTarget - epsMinus);
            Dscalar costPlus = (epsilonTarget - epsPlus) * (epsilonTarget - epsPlus);
            Dscalar gradient = (costPlus - costMinus) / (2.0 * h);

            h_etGrad.data[forwardIndex] = gradient;
            h_etGrad.data[reverseIndex] = gradient;

            // --- restore and re-relax, so the next junction is perturbed
            //     around the same reference configuration ---
            h_et.data[forwardIndex] = referenceTensions[forwardIndex];
            h_et.data[reverseIndex] = referenceTensions[reverseIndex];
            runFireLoop(fire, sim, fdFireDt, fdForceTol, fdOuterRounds, fdInnerIterations);
        }
    }
}

int main(int argc, char *argv[])
{
    // =========================
    // 1) Parse command line args
    // =========================
    const int expectedArgs = 38; // program name + 37 parameters
    if (argc < expectedArgs)
    {
        cout << "Usage: gd outputDir seed numCells A0 KA KP dt FireTol initSteps "
             << "TensionDynamicsSteps TuningRateGD SamplingRate T1Threshold "
             << "KA_init KP_init KA_dyn KP_dyn T1EdgeTensionReset "
             << "InitialAvgP ThetaEdgeFraction InitialVerticalEdgeFraction InitConfTol "
             << "NumP0Mean P0MeanLow P0MeanHigh NumP0STD P0STDLow P0STDHigh "
             << "NumTensionMean TensionMeanLow TensionMeanHigh NumTensionSTD TensionSTDLow TensionSTDHigh "
             << "FireTolInitConf TargetEps FiniteDiffStep"
             << endl;
        return 1;
    }

    string outputDir = argv[1];                          // output directory for the text and NetCDF files
    int rngSeed = atoi(argv[2]);                         // base RNG seed / sample index
    int numCells = atoi(argv[3]);                        // number of cells N

    Dscalar areaPref = atof(argv[4]);                    // target cell area A0
    Dscalar areaModulus = atof(argv[5]);                 // K_A for the initial base relaxation
    Dscalar perimeterModulus = atof(argv[6]);            // K_P for the initial base relaxation

    Dscalar fireDt = atof(argv[7]);                      // FIRE time step
    Dscalar fireTol = atof(argv[8]);                     // force tolerance for the production minimizations
    int fireOuterRounds = atoi(argv[9]);                 // number of FIRE restart rounds

    int tensionDynamicsSteps = atoi(argv[10]);           // number of gradient-descent iterations
    Dscalar tuningRateGD = atof(argv[11]);               // gamma_GD of Eq. (5); absorbs the update time step
    int samplingRate = atoi(argv[12]);                   // sample observables every this many iterations

    Dscalar t1Threshold = atof(argv[13]);                // edge length below which a T1 is performed

    Dscalar areaModulusInitSearch = atof(argv[14]);      // K_A used while searching for the initial state
    Dscalar perimeterModulusInitSearch = atof(argv[15]); // K_P used while searching for the initial state
    Dscalar areaModulusDynamics = atof(argv[16]);        // K_A used during the tuning protocol
    Dscalar perimeterModulusDynamics = atof(argv[17]);   // K_P used during the tuning protocol

    Dscalar t1EdgeTensionResetValue = atof(argv[18]);    // optional fixed post-T1 tension (see note below)

    Dscalar targetAvgCellShape = atof(argv[19]);         // experimental average cell shape at CE onset
    Dscalar thetaEdgeFractionDeg = atof(argv[20]);       // half-window (degrees) defining a "vertical" edge
    Dscalar targetVerticalEdgeFraction = atof(argv[21]); // experimental vertical-edge fraction at CE onset
    Dscalar initConfTolerance = atof(argv[22]);          // tolerance for accepting the initial state

    int numP0Mean = atoi(argv[23]);                      // p0 mean sweep: number of values ...
    Dscalar p0MeanLow = atof(argv[24]);                  // ... lower bound ...
    Dscalar p0MeanHigh = atof(argv[25]);                 // ... upper bound

    int numP0Std = atoi(argv[26]);                       // p0 std sweep
    Dscalar p0StdLow = atof(argv[27]);
    Dscalar p0StdHigh = atof(argv[28]);

    int numTensionMean = atoi(argv[29]);                 // active-tension mean sweep
    Dscalar tensionMeanLow = atof(argv[30]);
    Dscalar tensionMeanHigh = atof(argv[31]);

    int numTensionStd = atoi(argv[32]);                  // active-tension std sweep
    Dscalar tensionStdLow = atof(argv[33]);
    Dscalar tensionStdHigh = atof(argv[34]);

    Dscalar fireTolInitConf = atof(argv[35]);            // looser force tolerance for the initial-state search

    Dscalar targetEps = atof(argv[36]);                  // eps_target of the cost function
    Dscalar finiteDiffStep = atof(argv[37]);             // h of the central finite difference

    // =========================
    // 2) Runtime setup
    // =========================
    // The finite-difference gradient is computed on the CPU, so this driver is CPU-only;
    // set gpuIndex >= 0 only if you also revisit that routine.
    int gpuIndex = -1;
    bool useGPU = false;
    if (gpuIndex >= 0)
    {
        if (!chooseGPU(gpuIndex))
            return 1;
        cudaSetDevice(gpuIndex);
        useGPU = true;
    }

    int fireInnerIterations = 1000; // FIRE iterations per restart round
    bool reproducible = true;       // fixed RNG stream, so runs can be repeated
    bool runSPV = false;            // initialize from a Voronoi tessellation, not an SPV run

    // Relaxation settings used inside the finite-difference loop. They are
    // tighter and shorter than the production settings: the strain difference
    // being measured is small, so the residual force must be small, but each of
    // the O(N) relaxations starts from an already-relaxed configuration and
    // therefore converges quickly.
    Dscalar fdFireDt = 5e-4;
    Dscalar fdForceTol = 1e-10;
    int fdOuterRounds = 10;
    int fdInnerIterations = 10000;

    Dscalar thetaEdgeFractionRad = thetaEdgeFractionDeg * (M_PI / 180.0);
    int numEdges = 3 * (2 * numCells); // trivalent network: Nvertices = 2 * Ncells

    // Parsed but unused: this protocol resets the post-T1 tension to the running
    // network average <T> rather than to a fixed value. The argument is kept in
    // the interface so that a fixed reset can be switched on where marked below.
    (void)t1EdgeTensionResetValue;

    // =========================
    // 3) Sweep lists
    // =========================
    std::vector<double> p0MeanList = buildLinearGrid(numP0Mean, p0MeanLow, p0MeanHigh);
    std::vector<double> p0StdList = buildLinearGrid(numP0Std, p0StdLow, p0StdHigh);
    std::vector<double> tensionMeanList = buildLinearGrid(numTensionMean, tensionMeanLow, tensionMeanHigh);
    std::vector<double> tensionStdList = buildLinearGrid(numTensionStd, tensionStdLow, tensionStdHigh);

    if (p0MeanList.empty() || p0StdList.empty() || tensionMeanList.empty() || tensionStdList.empty())
    {
        cout << "Each of NumP0Mean, NumP0STD, NumTensionMean, NumTensionSTD must be >= 1." << endl;
        return 1;
    }

    // =========================
    // 4) Output files
    // =========================
    ofstream outFile((outputDir + "vertex_Ncell" + intToString(numCells) + "sample" + intToString(rngSeed) + ".txt").c_str());
    outFile.precision(17);

    ofstream outInitSearch((outputDir + "vertex_Ncell" + intToString(numCells) + "sample" + intToString(rngSeed) + "_initial_conf_steps_info.txt").c_str());
    outInitSearch.precision(17);

    string dataname = outputDir + "vertex_Ncell" + intToString(numCells) + "sample" + intToString(rngSeed) + ".nc";
    AVMDatabaseNetCDF ncdat(2 * numCells, dataname, NcFile::Replace);

    string datanameOriginal = outputDir + "vertex_Ncell" + intToString(numCells) + "sample" + intToString(rngSeed) + "_original.nc";
    AVMDatabaseNetCDF ncdatOriginal(2 * numCells, datanameOriginal, NcFile::Replace);

    // -------------------------
    // 5) Construct the tissue
    // -------------------------
    Dscalar baseP0 = p0MeanList[0];
    Dscalar selectedP0Mean = baseP0;

    shared_ptr<VertexQuadraticEnergy> avm =
        make_shared<VertexQuadraticEnergy>(numCells, 1.0, baseP0, reproducible, 1001 * rngSeed, runSPV);

    avm->setCellPreferencesUniform(areaPref, baseP0);
    avm->setModuliUniform(areaModulus, perimeterModulus);
    avm->setT1Threshold(t1Threshold);

    // The box pure-shear strain eps is relaxed together with the vertex
    // positions;
    avm->setBoxStrainXStrainY_DOF(true);

    // --------------------------------------
    // 6) Relax the passive tissue
    // --------------------------------------
    Dscalar maxForce = runFireMinimization(avm, useGPU, fireDt, fireTol,
                                           fireOuterRounds, fireInnerIterations);

    avm->ComputeEdgeCharacteristics();
    avm->ComputeEdgeSusceptibility();
    ncdat.WriteState(avm);

    writeSummaryLine(outFile, -1, baseP0, avm->ReturnStrainXStrainY().x, avm, maxForce);

    // -------------------------------------------------
    // 7) Reference state for the initial-state search
    // -------------------------------------------------
    avm->InitializeEdgeTensions();
    avm->setAddEdgeTensionEnergy(true);
    avm->setModuliUniform(areaModulusInitSearch, perimeterModulusInitSearch);

    maxForce = runFireMinimization(avm, useGPU, fireDt, fireTol,
                                   fireOuterRounds, fireInnerIterations);

    ncdatOriginal.WriteState(avm);

    Dscalar avgShape = avm->reportq();
    Dscalar verticalEdgeFraction = avm->ComputeFractionVerticalEdges(thetaEdgeFractionRad);

    outInitSearch << -1 << " " << -1 << " " << -1 << " " << -1 << " "
                  << -1 << " " << -1 << " " << -1 << " " << -1 << " "
                  << avm->ReturnStrainXStrainY().x << " " << avgShape << " " << verticalEdgeFraction << endl;

    // ------------------------------------------------------
    // 8) Search for an initial state matching experiment
    //
    // Identical to the search in local_rule.cpp and external_shear.cpp, so that
    // all protocols start from statistically equivalent initial states.
    // ------------------------------------------------------
    avm->SetResetT1EdgePropertiesAfterTransition(true);

    const int maxRandomTrials = 20;
    bool foundInitialConf = false;

    for (int p0MeanIter = 0; p0MeanIter < numP0Mean && !foundInitialConf; ++p0MeanIter)
    {
        for (int p0StdIter = 0; p0StdIter < numP0Std && !foundInitialConf; ++p0StdIter)
        {
            Dscalar p0Mean = p0MeanList[p0MeanIter];
            Dscalar p0Std = p0StdList[p0StdIter];

            for (int tensionMeanIter = 0; tensionMeanIter < numTensionMean && !foundInitialConf; ++tensionMeanIter)
            {
                for (int tensionStdIter = 0; tensionStdIter < numTensionStd && !foundInitialConf; ++tensionStdIter)
                {
                    Dscalar tensionMean = tensionMeanList[tensionMeanIter];
                    Dscalar tensionStd = tensionStdList[tensionStdIter];

                    bool foundGoodSample = false;
                    for (int randomTrial = 0; randomTrial < maxRandomTrials; ++randomTrial)
                    {
                        ncdatOriginal.ReadState(avm, 0, false);

                        int localSeed = 1001 * rngSeed * (randomTrial + 1);
                        avm->InitializeEdgeTensionsNormalRand(tensionMean, tensionStd, localSeed);
                        avm->setCellPreferencesNormalRand(areaPref, p0Mean, p0Std, localSeed);

                        // Reset the box to the undeformed square. The box shape
                        // and the internal pure-shear variable have to be reset
                        // together, since the model rebuilds the box from
                        // eps_pure_shear whenever that degree of freedom is free.
                        avm->eps_pure_shear = 0.0;
                        avm->Box->setGeneral(sqrt(numCells), 0.0, 0.0, sqrt(numCells));

                        // Post-T1 tension reset value, <T> for the current network.
                        // Replace with t1EdgeTensionResetValue for a fixed reset instead.
                        avm->SetT1EdgeTension(avm->ReturnAverageEdgeTensions());

                        maxForce = runFireMinimization(avm, useGPU, fireDt, fireTolInitConf,
                                                       fireOuterRounds, fireInnerIterations,
                                                       1e-3 /* abort samples that stall */);

                        if (maxForce < fireTolInitConf)
                        {
                            foundGoodSample = true;
                            break;
                        }
                    }

                    avgShape = avm->reportq();
                    verticalEdgeFraction = avm->ComputeFractionVerticalEdges(thetaEdgeFractionRad);

                    outInitSearch << p0MeanIter << " " << p0Mean << " "
                                  << p0StdIter << " " << p0Std << " "
                                  << tensionMeanIter << " " << tensionMean << " "
                                  << tensionStdIter << " " << tensionStd << " "
                                  << avm->ReturnStrainXStrainY().x << " " << avgShape << " "
                                  << verticalEdgeFraction << endl;

                    if (foundGoodSample &&
                        (fabs(avgShape - targetAvgCellShape) < initConfTolerance) &&
                        (fabs(verticalEdgeFraction - targetVerticalEdgeFraction) < initConfTolerance))
                    {
                        selectedP0Mean = p0Mean;
                        foundInitialConf = true;
                    }
                }
            }
        }
    }

    if (!foundInitialConf)
        cout << "Warning: no (p0, tension) tuple matched the experimental targets within tolerance; "
             << "continuing from the last state visited." << endl;

    // =========================================
    // 9) Gradient-descent tension dynamics
    // =========================================
    avm->setModuliUniform(areaModulusDynamics, perimeterModulusDynamics);
    avm->SetResetT1EdgePropertiesAfterTransition(true);

    for (int tensionIter = 0; tensionIter < tensionDynamicsSteps; ++tensionIter)
    {
        // Keep the post-T1 reset value equal to the current network average.
        avm->SetT1EdgeTension(avm->ReturnAverageEdgeTensions());

        computeEdgeTensionGradientsFiniteDifference(avm, targetEps, finiteDiffStep,
                                                    fdFireDt, fdForceTol,
                                                    fdOuterRounds, fdInnerIterations);

        // Descend the cost function. The array handles are scoped to
        // this block so that they are released before the relaxation below.
        {
            ArrayHandle<Dscalar> h_et(avm->EdgeTension, access_location::host, access_mode::readwrite);
            ArrayHandle<Dscalar> h_etGrad(avm->EdgeTensionGrad, access_location::host, access_mode::read);
            for (int i = 0; i < numEdges; ++i)
                h_et.data[i] -= dt * tuningRateGD * h_etGrad.data[i];
        }

        maxForce = runFireMinimization(avm, useGPU, fireDt, fireTol,
                                       fireOuterRounds, fireInnerIterations);

        if (tensionIter % samplingRate == 0)
        {
            avm->ComputeEdgeCharacteristics();
            avm->ComputeEdgeSusceptibility();
            ncdat.WriteState(avm);

            writeSummaryLine(outFile, tensionIter, selectedP0Mean,
                             avm->ReturnStrainXStrainY().x, avm, maxForce);

            cout << "iteration " << tensionIter
                 << " // p0 mean " << selectedP0Mean
                 << " // strain " << avm->ReturnStrainXStrainY().x
                 << " // energy " << avm->computeEnergy() << endl;
        }
    }

    outInitSearch.close();
    outFile.close();

    if (useGPU)
        cudaDeviceReset();

    return 0;
}
